CREATE TABLE table_preagg_campaign_ads_day_raw_test_100dim_200metric (
  -- Time dimensions (2 columns)
  insert_hour DATETIME NULL,
  event_day DATE NULL,
  
  -- ID dimensions (20 columns)
  advertiser_id BIGINT(20) NULL,
  campaign_id BIGINT(20) NULL,
  ad_id BIGINT(20) NULL,
  ad_group_id BIGINT(20) NULL,
  creative_id BIGINT(20) NULL,
  user_id BIGINT(20) NULL,
  device_id BIGINT(20) NULL,
  account_id BIGINT(20) NULL,
  publisher_id BIGINT(20) NULL,
  site_id BIGINT(20) NULL,
  placement_id BIGINT(20) NULL,
  channel_id BIGINT(20) NULL,
  region_id BIGINT(20) NULL,
  city_id BIGINT(20) NULL,
  category_id BIGINT(20) NULL,
  subcategory_id BIGINT(20) NULL,
  brand_id BIGINT(20) NULL,
  product_id BIGINT(20) NULL,
  order_id BIGINT(20) NULL,
  session_id BIGINT(20) NULL,
  
  -- Integer dimensions (20 columns)
  dim_int_1 INT NULL,
  dim_int_2 INT NULL,
  dim_int_3 INT NULL,
  dim_int_4 INT NULL,
  dim_int_5 INT NULL,
  dim_int_6 INT NULL,
  dim_int_7 INT NULL,
  dim_int_8 INT NULL,
  dim_int_9 INT NULL,
  dim_int_10 INT NULL,
  dim_int_11 INT NULL,
  dim_int_12 INT NULL,
  dim_int_13 INT NULL,
  dim_int_14 INT NULL,
  dim_int_15 INT NULL,
  dim_int_16 INT NULL,
  dim_int_17 INT NULL,
  dim_int_18 INT NULL,
  dim_int_19 INT NULL,
  dim_int_20 INT NULL,
  
  -- BigInt dimensions (10 columns)
  dim_bigint_1 BIGINT(20) NULL,
  dim_bigint_2 BIGINT(20) NULL,
  dim_bigint_3 BIGINT(20) NULL,
  dim_bigint_4 BIGINT(20) NULL,
  dim_bigint_5 BIGINT(20) NULL,
  dim_bigint_6 BIGINT(20) NULL,
  dim_bigint_7 BIGINT(20) NULL,
  dim_bigint_8 BIGINT(20) NULL,
  dim_bigint_9 BIGINT(20) NULL,
  dim_bigint_10 BIGINT(20) NULL,
  
  -- Varchar dimensions (22 columns)
  dim_varchar_1 VARCHAR(100) NULL,
  dim_varchar_2 VARCHAR(100) NULL,
  dim_varchar_3 VARCHAR(100) NULL,
  dim_varchar_4 VARCHAR(100) NULL,
  dim_varchar_5 VARCHAR(100) NULL,
  dim_varchar_6 VARCHAR(100) NULL,
  dim_varchar_7 VARCHAR(100) NULL,
  dim_varchar_8 VARCHAR(100) NULL,
  dim_varchar_9 VARCHAR(100) NULL,
  dim_varchar_10 VARCHAR(100) NULL,
  dim_varchar_11 VARCHAR(200) NULL,
  dim_varchar_12 VARCHAR(200) NULL,
  dim_varchar_13 VARCHAR(200) NULL,
  dim_varchar_14 VARCHAR(200) NULL,
  dim_varchar_15 VARCHAR(200) NULL,
  dim_varchar_16 VARCHAR(200) NULL,
  dim_varchar_17 VARCHAR(200) NULL,
  dim_varchar_18 VARCHAR(200) NULL,
  dim_varchar_19 VARCHAR(200) NULL,
  dim_varchar_20 VARCHAR(200) NULL,
  dim_varchar_21 VARCHAR(50) NULL,
  dim_varchar_22 VARCHAR(50) NULL,
  
  -- Char dimensions (8 columns)
  dim_char_1 CHAR(20) NULL,
  dim_char_2 CHAR(20) NULL,
  dim_char_3 CHAR(20) NULL,
  dim_char_4 CHAR(50) NULL,
  dim_char_5 CHAR(50) NULL,
  dim_char_6 CHAR(50) NULL,
  dim_char_7 CHAR(50) NULL,
  dim_char_8 CHAR(50) NULL,
  
  -- Boolean dimensions (5 columns)
  dim_bool_1 BOOLEAN NULL,
  dim_bool_2 BOOLEAN NULL,
  dim_bool_3 BOOLEAN NULL,
  dim_bool_4 BOOLEAN NULL,
  dim_bool_5 BOOLEAN NULL,
  
  -- SmallInt dimensions (3 columns)
  dim_smallint_1 SMALLINT NULL,
  dim_smallint_2 SMALLINT NULL,
  dim_smallint_3 SMALLINT NULL,
  
  dim_int_21 INT NULL,
  dim_int_22 INT NULL,
  dim_int_23 INT NULL,
  dim_int_24 INT NULL,
  dim_int_25 INT NULL,
  
  dim_varchar_23 VARCHAR(100) NULL,
  dim_varchar_24 VARCHAR(100) NULL,
  dim_varchar_25 VARCHAR(200) NULL,
  dim_varchar_26 VARCHAR(200) NULL,
  dim_varchar_27 VARCHAR(50) NULL,
  
  impressions BIGINT(20) SUM NULL,
  clicks BIGINT(20) SUM NULL,
  views BIGINT(20) SUM NULL,
  conversions BIGINT(20) SUM NULL,
  installs BIGINT(20) SUM NULL,
  metric_bigint_sum_1 BIGINT(20) SUM NULL,
  metric_bigint_sum_2 BIGINT(20) SUM NULL,
  metric_bigint_sum_3 BIGINT(20) SUM NULL,
  metric_bigint_sum_4 BIGINT(20) SUM NULL,
  metric_bigint_sum_5 BIGINT(20) SUM NULL,
  metric_bigint_sum_6 BIGINT(20) SUM NULL,
  metric_bigint_sum_7 BIGINT(20) SUM NULL,
  metric_bigint_sum_8 BIGINT(20) SUM NULL,
  metric_bigint_sum_9 BIGINT(20) SUM NULL,
  metric_bigint_sum_10 BIGINT(20) SUM NULL,
  metric_bigint_sum_11 BIGINT(20) SUM NULL,
  metric_bigint_sum_12 BIGINT(20) SUM NULL,
  metric_bigint_sum_13 BIGINT(20) SUM NULL,
  metric_bigint_sum_14 BIGINT(20) SUM NULL,
  metric_bigint_sum_15 BIGINT(20) SUM NULL,
  metric_bigint_sum_16 BIGINT(20) SUM NULL,
  metric_bigint_sum_17 BIGINT(20) SUM NULL,
  metric_bigint_sum_18 BIGINT(20) SUM NULL,
  metric_bigint_sum_19 BIGINT(20) SUM NULL,
  metric_bigint_sum_20 BIGINT(20) SUM NULL,
  metric_bigint_sum_21 BIGINT(20) SUM NULL,
  metric_bigint_sum_22 BIGINT(20) SUM NULL,
  metric_bigint_sum_23 BIGINT(20) SUM NULL,
  metric_bigint_sum_24 BIGINT(20) SUM NULL,
  metric_bigint_sum_25 BIGINT(20) SUM NULL,
  metric_bigint_sum_26 BIGINT(20) SUM NULL,
  metric_bigint_sum_27 BIGINT(20) SUM NULL,
  metric_bigint_sum_28 BIGINT(20) SUM NULL,
  metric_bigint_sum_29 BIGINT(20) SUM NULL,
  metric_bigint_sum_30 BIGINT(20) SUM NULL,
  metric_bigint_sum_31 BIGINT(20) SUM NULL,
  metric_bigint_sum_32 BIGINT(20) SUM NULL,
  metric_bigint_sum_33 BIGINT(20) SUM NULL,
  metric_bigint_sum_34 BIGINT(20) SUM NULL,
  metric_bigint_sum_35 BIGINT(20) SUM NULL,
  metric_bigint_sum_36 BIGINT(20) SUM NULL,
  metric_bigint_sum_37 BIGINT(20) SUM NULL,
  metric_bigint_sum_38 BIGINT(20) SUM NULL,
  metric_bigint_sum_39 BIGINT(20) SUM NULL,
  metric_bigint_sum_40 BIGINT(20) SUM NULL,
  metric_bigint_sum_41 BIGINT(20) SUM NULL,
  metric_bigint_sum_42 BIGINT(20) SUM NULL,
  metric_bigint_sum_43 BIGINT(20) SUM NULL,
  metric_bigint_sum_44 BIGINT(20) SUM NULL,
  metric_bigint_sum_45 BIGINT(20) SUM NULL,
  metric_bigint_sum_46 BIGINT(20) SUM NULL,
  metric_bigint_sum_47 BIGINT(20) SUM NULL,
  metric_bigint_sum_48 BIGINT(20) SUM NULL,
  metric_bigint_sum_49 BIGINT(20) SUM NULL,
  metric_bigint_sum_50 BIGINT(20) SUM NULL,
  metric_bigint_sum_51 BIGINT(20) SUM NULL,
  metric_bigint_sum_52 BIGINT(20) SUM NULL,
  metric_bigint_sum_53 BIGINT(20) SUM NULL,
  metric_bigint_sum_54 BIGINT(20) SUM NULL,
  metric_bigint_sum_55 BIGINT(20) SUM NULL,
  metric_bigint_sum_56 BIGINT(20) SUM NULL,
  metric_bigint_sum_57 BIGINT(20) SUM NULL,
  metric_bigint_sum_58 BIGINT(20) SUM NULL,
  metric_bigint_sum_59 BIGINT(20) SUM NULL,
  metric_bigint_sum_60 BIGINT(20) SUM NULL,
  metric_bigint_sum_61 BIGINT(20) SUM NULL,
  metric_bigint_sum_62 BIGINT(20) SUM NULL,
  metric_bigint_sum_63 BIGINT(20) SUM NULL,
  metric_bigint_sum_64 BIGINT(20) SUM NULL,
  metric_bigint_sum_65 BIGINT(20) SUM NULL,
  metric_bigint_sum_66 BIGINT(20) SUM NULL,
  metric_bigint_sum_67 BIGINT(20) SUM NULL,
  metric_bigint_sum_68 BIGINT(20) SUM NULL,
  metric_bigint_sum_69 BIGINT(20) SUM NULL,
  metric_bigint_sum_70 BIGINT(20) SUM NULL,
  
  -- Double SUM metrics (35 columns) - Amount metrics
  spend DOUBLE SUM NULL,
  revenue DOUBLE SUM NULL,
  cost DOUBLE SUM NULL,
  profit DOUBLE SUM NULL,
  metric_double_sum_1 DOUBLE SUM NULL,
  metric_double_sum_2 DOUBLE SUM NULL,
  metric_double_sum_3 DOUBLE SUM NULL,
  metric_double_sum_4 DOUBLE SUM NULL,
  metric_double_sum_5 DOUBLE SUM NULL,
  metric_double_sum_6 DOUBLE SUM NULL,
  metric_double_sum_7 DOUBLE SUM NULL,
  metric_double_sum_8 DOUBLE SUM NULL,
  metric_double_sum_9 DOUBLE SUM NULL,
  metric_double_sum_10 DOUBLE SUM NULL,
  metric_double_sum_11 DOUBLE SUM NULL,
  metric_double_sum_12 DOUBLE SUM NULL,
  metric_double_sum_13 DOUBLE SUM NULL,
  metric_double_sum_14 DOUBLE SUM NULL,
  metric_double_sum_15 DOUBLE SUM NULL,
  metric_double_sum_16 DOUBLE SUM NULL,
  metric_double_sum_17 DOUBLE SUM NULL,
  metric_double_sum_18 DOUBLE SUM NULL,
  metric_double_sum_19 DOUBLE SUM NULL,
  metric_double_sum_20 DOUBLE SUM NULL,
  metric_double_sum_21 DOUBLE SUM NULL,
  metric_double_sum_22 DOUBLE SUM NULL,
  metric_double_sum_23 DOUBLE SUM NULL,
  metric_double_sum_24 DOUBLE SUM NULL,
  metric_double_sum_25 DOUBLE SUM NULL,
  metric_double_sum_26 DOUBLE SUM NULL,
  metric_double_sum_27 DOUBLE SUM NULL,
  metric_double_sum_28 DOUBLE SUM NULL,
  metric_double_sum_29 DOUBLE SUM NULL,
  metric_double_sum_30 DOUBLE SUM NULL,
  
  -- Decimal SUM metrics (10 columns)
  metric_decimal_sum_1 DECIMAL(18,2) SUM NULL,
  metric_decimal_sum_2 DECIMAL(18,2) SUM NULL,
  metric_decimal_sum_3 DECIMAL(18,2) SUM NULL,
  metric_decimal_sum_4 DECIMAL(18,2) SUM NULL,
  metric_decimal_sum_5 DECIMAL(18,2) SUM NULL,
  metric_decimal_sum_6 DECIMAL(20,4) SUM NULL,
  metric_decimal_sum_7 DECIMAL(20,4) SUM NULL,
  metric_decimal_sum_8 DECIMAL(20,4) SUM NULL,
  metric_decimal_sum_9 DECIMAL(20,4) SUM NULL,
  metric_decimal_sum_10 DECIMAL(20,4) SUM NULL,
  
  -- Double MAX metrics (15 columns)
  metric_double_max_1 DOUBLE MAX NULL,
  metric_double_max_2 DOUBLE MAX NULL,
  metric_double_max_3 DOUBLE MAX NULL,
  metric_double_max_4 DOUBLE MAX NULL,
  metric_double_max_5 DOUBLE MAX NULL,
  metric_double_max_6 DOUBLE MAX NULL,
  metric_double_max_7 DOUBLE MAX NULL,
  metric_double_max_8 DOUBLE MAX NULL,
  metric_double_max_9 DOUBLE MAX NULL,
  metric_double_max_10 DOUBLE MAX NULL,
  metric_double_max_11 DOUBLE MAX NULL,
  metric_double_max_12 DOUBLE MAX NULL,
  metric_double_max_13 DOUBLE MAX NULL,
  metric_double_max_14 DOUBLE MAX NULL,
  metric_double_max_15 DOUBLE MAX NULL,
  
  -- Double MIN metrics (10 columns)
  metric_double_min_1 DOUBLE MIN NULL,
  metric_double_min_2 DOUBLE MIN NULL,
  metric_double_min_3 DOUBLE MIN NULL,
  metric_double_min_4 DOUBLE MIN NULL,
  metric_double_min_5 DOUBLE MIN NULL,
  metric_double_min_6 DOUBLE MIN NULL,
  metric_double_min_7 DOUBLE MIN NULL,
  metric_double_min_8 DOUBLE MIN NULL,
  metric_double_min_9 DOUBLE MIN NULL,
  metric_double_min_10 DOUBLE MIN NULL,
  
  -- BigInt MAX metrics (10 columns)
  metric_bigint_max_1 BIGINT(20) MAX NULL,
  metric_bigint_max_2 BIGINT(20) MAX NULL,
  metric_bigint_max_3 BIGINT(20) MAX NULL,
  metric_bigint_max_4 BIGINT(20) MAX NULL,
  metric_bigint_max_5 BIGINT(20) MAX NULL,
  metric_bigint_max_6 BIGINT(20) MAX NULL,
  metric_bigint_max_7 BIGINT(20) MAX NULL,
  metric_bigint_max_8 BIGINT(20) MAX NULL,
  metric_bigint_max_9 BIGINT(20) MAX NULL,
  metric_bigint_max_10 BIGINT(20) MAX NULL,
  
  -- Varchar REPLACE metrics (10 columns)
  metric_varchar_replace_1 VARCHAR(100) REPLACE NULL,
  metric_varchar_replace_2 VARCHAR(100) REPLACE NULL,
  metric_varchar_replace_3 VARCHAR(100) REPLACE NULL,
  metric_varchar_replace_4 VARCHAR(100) REPLACE NULL,
  metric_varchar_replace_5 VARCHAR(100) REPLACE NULL,
  metric_varchar_replace_6 VARCHAR(200) REPLACE NULL,
  metric_varchar_replace_7 VARCHAR(200) REPLACE NULL,
  metric_varchar_replace_8 VARCHAR(200) REPLACE NULL,
  metric_varchar_replace_9 VARCHAR(200) REPLACE NULL,
  metric_varchar_replace_10 VARCHAR(200) REPLACE NULL,
  
  -- Bitmap UNION metrics (10 columns)
  unique_users BITMAP BITMAP_UNION NULL,
  unique_devices BITMAP BITMAP_UNION NULL,
  metric_bitmap_1 BITMAP BITMAP_UNION NULL,
  metric_bitmap_2 BITMAP BITMAP_UNION NULL,
  metric_bitmap_3 BITMAP BITMAP_UNION NULL,
  metric_bitmap_4 BITMAP BITMAP_UNION NULL,
  metric_bitmap_5 BITMAP BITMAP_UNION NULL,
  metric_bitmap_6 BITMAP BITMAP_UNION NULL,
  metric_bitmap_7 BITMAP BITMAP_UNION NULL,
  metric_bitmap_8 BITMAP BITMAP_UNION NULL,
  
  -- HLL UNION metrics (5 columns)
  metric_hll_1 HLL HLL_UNION NULL,
  metric_hll_2 HLL HLL_UNION NULL,
  metric_hll_3 HLL HLL_UNION NULL,
  metric_hll_4 HLL HLL_UNION NULL,
  metric_hll_5 HLL HLL_UNION NULL,
  
  -- REPLACE_IF_NOT_NULL metrics (10 columns)
  metric_replace_if_not_null_bigint_1 BIGINT(20) REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_bigint_2 BIGINT(20) REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_double_1 DOUBLE REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_double_2 DOUBLE REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_varchar_1 VARCHAR(100) REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_varchar_2 VARCHAR(200) REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_decimal_1 DECIMAL(18,2) REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_decimal_2 DECIMAL(20,4) REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_int_1 INT REPLACE_IF_NOT_NULL NULL,
  metric_replace_if_not_null_int_2 INT REPLACE_IF_NOT_NULL NULL,
  
  -- PERCENTILE_UNION metrics (10 columns)
  metric_percentile_1 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_2 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_3 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_4 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_5 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_6 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_7 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_8 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_9 PERCENTILE PERCENTILE_UNION NULL,
  metric_percentile_10 PERCENTILE PERCENTILE_UNION NULL,
  
  -- JSON REPLACE metrics (2 columns)
  metric_json_replace_1 JSON REPLACE NULL,
  metric_json_replace_2 JSON REPLACE NULL,
  
  -- ARRAY REPLACE metrics (4 columns)
  metric_array_int_replace_1 ARRAY<INT> REPLACE NULL,
  metric_array_bigint_replace_1 ARRAY<BIGINT> REPLACE NULL,
  metric_array_varchar_replace_1 ARRAY<VARCHAR(100)> REPLACE NULL,
  metric_array_double_replace_1 ARRAY<DOUBLE> REPLACE NULL,
  
  -- MAP REPLACE metrics (2 columns)
  metric_map_int_int_replace_1 MAP<INT, INT> REPLACE NULL,
  metric_map_varchar_varchar_replace_1 MAP<VARCHAR(100), VARCHAR(100)> REPLACE NULL,
  
  -- STRUCT REPLACE_IF_NOT_NULL metrics (2 columns)
  metric_struct_replace_if_not_null_1 STRUCT<id INT, name VARCHAR(100), value DOUBLE> REPLACE_IF_NOT_NULL NULL,
  metric_struct_replace_if_not_null_2 STRUCT<user_id BIGINT, user_name VARCHAR(200), age INT, active BOOLEAN> REPLACE_IF_NOT_NULL NULL
  
  -- Total: 75 + 35 + 10 + 15 + 10 + 10 + 10 + 10 + 5 + 10 + 10 + 10 = 200 aggregate columns
)
ENGINE=OLAP
AGGREGATE KEY(
  insert_hour, event_day,
  advertiser_id, campaign_id, ad_id, ad_group_id, creative_id, user_id, device_id, account_id,
  publisher_id, site_id, placement_id, channel_id, region_id, city_id, category_id, subcategory_id, brand_id, product_id,
  order_id, session_id,
  dim_int_1, dim_int_2, dim_int_3, dim_int_4, dim_int_5, dim_int_6, dim_int_7, dim_int_8,
  dim_int_9, dim_int_10, dim_int_11, dim_int_12, dim_int_13, dim_int_14, dim_int_15, dim_int_16, dim_int_17, dim_int_18,
  dim_int_19, dim_int_20,
  dim_bigint_1, dim_bigint_2, dim_bigint_3, dim_bigint_4, dim_bigint_5, dim_bigint_6, dim_bigint_7,
  dim_bigint_8, dim_bigint_9, dim_bigint_10,
  dim_varchar_1, dim_varchar_2, dim_varchar_3, dim_varchar_4, dim_varchar_5,
  dim_varchar_6, dim_varchar_7, dim_varchar_8, dim_varchar_9, dim_varchar_10,
  dim_varchar_11, dim_varchar_12, dim_varchar_13, dim_varchar_14, dim_varchar_15,
  dim_varchar_16, dim_varchar_17, dim_varchar_18, dim_varchar_19, dim_varchar_20,
  dim_varchar_21, dim_varchar_22,
  dim_char_1, dim_char_2, dim_char_3, dim_char_4, dim_char_5, dim_char_6, dim_char_7, dim_char_8,
  dim_bool_1, dim_bool_2, dim_bool_3, dim_bool_4, dim_bool_5,
  dim_smallint_1, dim_smallint_2, dim_smallint_3,
  dim_int_21, dim_int_22, dim_int_23, dim_int_24, dim_int_25,
  dim_varchar_23, dim_varchar_24, dim_varchar_25, dim_varchar_26, dim_varchar_27
)
PARTITION BY RANGE(event_day) (
  START ("2025-01-01") END ("2026-01-01") EVERY (INTERVAL 1 DAY)
)
DISTRIBUTED BY HASH(advertiser_id) BUCKETS 16
PROPERTIES (
  "replication_num" = "3",
  "storage_format" = "v2",
  "enable_persistent_index" = "true"
);
